### PR TITLE
Add an average method

### PR DESCRIPTION
**Pull request by jakobkogler**

### CODE REVIEW

**Comment by Maltysen** [comment]
I don't see the necessity to create a new dot-function. There are tons of overloads available in the dot-functions. Here are some the appropriate ones I could find: `B`, `.H`, `.O`, `.!`

**Comment by isaacg1** [comment]
I'd also prefer to see this as an overload.

**Comment by jakobkogler** [comment]
Is `.O` fine? I'm not really happy with it, but the other free tokens are equally bad.

**Comment by isaacg1** [comment]
Sounds fine.

**Pull request merged**
