### PR TITLE
Added safe mode to interpreter

### PR DESCRIPTION
**Pull request by Maltysen**
There was no point to having two different interpreters when a "safe-mode" flag could be added so I implemented that. It is kind of obviously ``-s`` or ``--safe``. I set a global variable ``safe_mode`` and decide what to do with ``$`` based on that. The part where you set ``literal_eval`` instead of ``eval`` has also been moved into a conditional. I copied all your security execution code over,, comments and all. I also updated the server so it calls ``pyth.py`` with ``-s``. I haven't tested the server, but the flags seem to work from the command line. This will make it easier to update the interpreter, especially the core parsing logic that is needlessly duplicated.

### CODE REVIEW

**Comment by Maltysen** [comment]
As I thought, I screwed up the server. I forgot about the timestamp request to ``safe_pyth.py``. Fixed and should be working now.

**Comment by isaacg1** [comment]
Looks good to me - this is a great idea!

**Comment by isaacg1** [comment]
Looks like there was a rather major bug in this - the enabling of literal_eval happened after the code was generated. This has been fixed.

**Comment by Maltysen** [comment]
Oh shoot, sorry didn't realize that.

**Pull request merged**
