### PR TITLE
Implemented enumerate.

### PR DESCRIPTION
**Pull request by orlp**

### CODE REVIEW

**Comment by orlp** [comment]
Fixes https://github.com/isaacg1/pyth/issues/56.

**Comment by isaacg1** [comment]
Thanks, but I already fixed it.

**Comment by orlp** [comment]
Hmm, I used `is_col` instead of `is_seq` though - I wonder which is more appropriate.

The docs say that enumerate is 'a map over an enumerate', and `m` uses `is_col`, so I think we should use `is_col` in `.e` as well.

**Comment by isaacg1** [comment]
I was just reverting to the way it was previously. I had is_seq because the python 2 docs say enumerate takes a sequence, but I checked the python 3 docs and they say iterator a.k.a. collection, so I'll switch it to is_col

**Pull request closed without merging**
