### PR TITLE
X - translate: use reversed 3rd arg if omitted

### PR DESCRIPTION
**Pull request by jakobkogler**
Also updated the docs and wrote a few tests.

### CODE REVIEW

**Comment by orlp** [comment]
I don't feel great about this feature request. It seems too obscure and not very useful.

This feature came up during one particular golfing challenge, but I don't see this being a useful re-usable tool for future challenges.

**Comment by isaacg1** [comment]
@orlp I've definitely wanted this feature for other challenges in the past, such as implementing rot13, or the palindrome with swapped parens contest. I think it's worth it.

**Comment by orlp** [comment]
@isaacg1  How is this any better for rot13? This is the shortest way of rot13'ing I know:

    XzG.<G13

**Comment by isaacg1** [comment]
@orlp You're right, nevermind.

**Pull request merged**
