### PR TITLE
Added fold operator

### PR DESCRIPTION
**Pull request by Maltysen**
While Pyth has a reduce function, it does not work on syntactical elements. I took advantage of the fact that a binary operator can never go before a control flow element (e.g. `*F`) and made `F` the fold operator. Just put a binary operator in front of an `F` and it shuffles it around to use reduce. I also had to put a default case into reduce to account for the fact that fold won't use any base case; it will be the first element. Because this is so similar to the augmented assignment thing, I put in a framework to deal with "syntactical sugar". This is also possible for `map` and `filter`, but I wanted to pass the framework and and example by you first. Also, note that I had to make the parser for fold use the next one in the `c_to_f` cycle, so I used indices to get it so I needed that space in the middle to make it consistent. To repeat, **that space is important**

P.S. Note that you can now take out product (`*F`), all (`&F`), and any(`|F`). I had to make `and` and `or` functions instead of syntax for this.

### CODE REVIEW

**Comment by jakobkogler** [comment]
`all` and `any` already have `.`-token: `.A` and `.E`. We could use these one's for something else now. 

`*F` is really sweet. Finally shorter factorials.

**Comment by isaacg1** [comment]
I like `*F` a lot. However, `&` and `|` need to be reverted, because your change makes them not short circuit, which is an important quality.

**Comment by orlp** [comment]
Why `F`, and not `R` for reduce?

**Comment by orlp** [comment]
As for more syntactical frameworks, I've been secretly starting work on a clean-sheet rewrite of Pyth. It involves an actual compiler pipeline (lexer -> parser -> codegen), which should allow us to more easily write syntactically complex features, handle corner cases and produce correct output. It will also deal with the file structure problem we have right now.

And finally, with the exception of `$` and partially `v`, we'll be able to write a native codegen at some point, making Pyth blazing fast.

https://github.com/orlp/pyth5

**Comment by Maltysen** [comment]
@orlp I was trying to make it like "Fold" from J and APL.

**Comment by isaacg1** [comment]
This had a bug, where it double counted the first entry. Will fix.

**Pull request merged**
