### PR TITLE
Added more Functions

### PR DESCRIPTION
**Pull request by Maltysen**
I implemented a bunch of the functions on the web-docs that weren't actually there ans some of my own.

Here's a list:

1. Format - ``.F``: Does string formatting. Uses ``.format()``, unpacks if seq, otherwise uses one element.
2. Id - ``.I``: Uses ``id()``
3. Complex constructor - ``.j``: Makes complex ``aj+b``.
4. Complex functions - ``.i``: Functions for uses with complex numbers, conjugate, real, imag, etc.
5. Sqrt - `.~` - take sqrt of number
6. Nth root - .` - Uses rational exponents to do any root.

### CODE REVIEW

**Comment by isaacg1** [comment]
Thanks for the additions. The web-doc issue you mention was actually that the functions were added, then removed, and the web-docs were updated until a bit later.

**Comment by orlp** [comment]
I do not agree with this one. This pull requests fills up the new namespace at a rate that's too fast for my comfort.

- I find `.F` useful now that it uses `.format()`, so I wouldn't mind keeping it.
- `.I` is just useless IMO.
- `.~` and .` should be removed. I've never had to calculate a square root, let alone an arbitrary root for a code challenge, and when I did it involved arbitrary precision. Either way, it's respectively only 1 or 2 characters longer than `^_.5` and `^ac1b`.
- I'd suggest to remove `.i` and `.j` _for now_, until we have had the time to discuss how all other functions should behave with complex numbers. It's basically a whole new type to the system, and can add a _lot_ of overloads, to the point where I'd say `.i` isn't even necessary.

**Comment by isaacg1** [comment]
Yeah, I really only liked `.F` and `.i` and `.j`. I can see the argument for `.i` and `.j`, and against. I'm going to remove all but `.F` Sorry Maltysen, but something that saves at most 1 character doesn't belong.

**Comment by orlp** [comment]
Note that I'm not _against_ `.j` per se (I suggested it a while back), but it just requires a lot of discussion what needs to be done.

**Comment by orlp** [comment]
https://github.com/isaacg1/pyth/issues/51

**Comment by Maltysen** [comment]
That seems fair. I just added all them cuz the webdocs said listed them and they weren't implemented.

**Comment by orlp** [comment]
@Maltysen  Then that was the bug :) They were added at one point and removed.

**Pull request merged**
