### PR TITLE
Update rev-doc.txt

### PR DESCRIPTION
**Pull request by kckennylau**

### CODE REVIEW

**Comment by isaacg1** [comment]
Hey Kenny, I don't think that the "See _,_ and_" really adds much, overall. Also, I don't understand the changes to ) and ; -lists, tuples, blocks, these are all covered under functions and statements.

**Comment by kckennylau** [comment]
So that when I search `[` I may be able to know how to close it.

**Comment by kckennylau** [comment]
I also fixed a typo somewhere.

**Comment by isaacg1** [comment]
I'm not going to accept this. Thanks for trying, though.

**Pull request closed without merging**
