### PR TITLE
Heroku Flask server

### PR DESCRIPTION
**Pull request by Tyilo**
Use Flask instead of CGI for the server.
This reduces complexity and makes it possible to run it on Heroku with ease.

`Procfile`, `runtime.txt` and `requirements.txt` are used by Heroku.

### CODE REVIEW

**Comment by Maltysen** [comment]
Yeah. The CGI thing with python wasn't sustainable (It only served cgi files and couldn't serve static files), just wanted to make it self-contained but this is much better. I noticed you kept my horrible work around the fact static files couldn't be served with sending the web-docs file with mode equals 1. Just make the mode 0 or 1 and request the actual web-docs.txt from the html page (assuming flask serves static files :))

**Comment by Tyilo** [comment]
Flask doesn't by default, but I made it do it.
So I should probably change that.

**Comment by Maltysen** [comment]
Also your other pull request should probably be closed.

**Comment by Tyilo** [comment]
If @isaacg1 somehow don't think this should be merged, he might merge the other.

**Comment by Maltysen** [comment]
Oh that makes sense

**Comment by Maltysen** [comment]
Well, I took mine down.

**Comment by isaacg1** [comment]
This seems like an even better Pyth server system, so I'll merge this one in.

**Pull request merged**
