### PR TITLE
Added RNG seeding

### PR DESCRIPTION
**Pull request by Maltysen**
Though not used very often, reproducibility is still comes up a fair amount in randomness challenges and `$random.seed()$` kills your score. I have put it into all non-`seq` of `.x` though it most often will be used with ints. I don't think that such a small part  of the namespace is a big price to pay for seeding.

### CODE REVIEW

**Comment by isaacg1** [comment]
Please update `doc.txt` and `web-doc.txt` accordingly.

**Comment by orlp** [comment]
`.x` needs error checking for type issues. This is not an issue with the pull request, it was missing in the first place.

**Comment by Maltysen** [comment]
K i'll add error checking and only allow `int` for the seed then.

**Comment by isaacg1** [comment]
Excellent, thank you.

**Pull request merged**
