### PR TITLE
Fix issue 181

### PR DESCRIPTION
**Pull request by muddyfish**
Extends `}`, Pin so it functions for cases where A > B

### CODE REVIEW

**Comment by jakobkogler** [comment]
Hi Simon.
Can you add one or two test cases to test.py?
This way we can automatically see if the implementation works.

**Comment by muddyfish** [comment]
I've just added some test cases (just so you know, test.py doesn't work under python3.5)

**Comment by jakobkogler** [comment]
@muddyfish Are you sure? What is exactly the problem?
I'm running Python 3.5.1 and it works fine for me.

**Comment by muddyfish** [comment]
I'm on python 3.5.1, failing with `TypeError: Required argument 'user_function' (pos 1) not found` in

```
File "~~~\pyth\pyth.py", line 568, in run_code
  saved_env = c.deepcopy(environment)
```

I believe this is because lru_cache fails to deepcopy properly in my version

**Pull request merged**
