### PR TITLE
Added .+ [deltas]

### PR DESCRIPTION
**Pull request by Steven-Hewitt**
.+  <seq> Deltas. Returns the differences between consecutive elements of A.

### CODE REVIEW

**Comment by Maltysen** [comment]
This seems good, but it may be better to add a met-op instead that one will be able to use for different operators.

**Comment by Steven-Hewitt** [comment]
Would you recommend that I keep it as .+ when switching to a met-op? All the current met-ops (if I remember correctly) are single-character commands.

**Comment by Maltysen** [comment]
I don't think anything prevents meta-ops from being double chars, but it might not be worth it in terms of golfiness if we can’t find a single char one.

**Comment by Steven-Hewitt** [comment]
The only single-char operation I can find without going into extended ASCII is the literal tab character, which would be a pain to insert into the online interpreter (or the REPL, for that matter.)

**Pull request merged**
